name: simplex-messaging
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/simplex-messaging#readme
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2020 Author name here
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring
  - containers
  - network
  - polysemy
  - singletons
  - stm

executables:
  simplex-messaging:
    source-dirs: src
    main: Main.hs

ghc-options:
  - -haddock
  - -O2
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
