name: simplex-messaging
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/simplex-chat/simplex-messaging#readme
license: AGPL-3
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
category: Web, System, Services, Cryptography
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - mtl
  - network
  - singletons
  - stm
  - unliftio-core
  - unliftio

executables:
  simplex-messaging:
    source-dirs: src
    main: Main.hs

library:
  source-dirs: src

tests:
  smp-server-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - simplex-messaging
      - hspec == 2.7.*

ghc-options:
  # - -haddock
  - -O0
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
